# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CueCli < Formula
  desc "Cue CLI — coordinate events from the command line"
  homepage "https://getcue.net/cli"
  version "6.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.6.0/cue_6.6.0_darwin_amd64.tar.gz"
      sha256 "a352cf15eed48f1d62a25128f830c53e8a01f16b6c15940efcab35a256cfe496"

      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.6.0/cue_6.6.0_darwin_arm64.tar.gz"
      sha256 "1d5033d2a8a1badddb07f34ce4559c0bb7c5231c514fac96cdeb2bd17bd5b03b"

      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.6.0/cue_6.6.0_linux_amd64.tar.gz"
      sha256 "9db325530948f16ca5c94c5060a8046c5d403711ed657d66bb74d4237d98ae4e"
      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.6.0/cue_6.6.0_linux_arm64.tar.gz"
      sha256 "dc65ee90eafb17915eb12ba2d3b1c7ef6453cebd759b5e27e5474c07935869a7"
      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
  end

  conflicts_with "cue"

  def caveats
    <<~EOS
      The 'cue' binary may conflict with the CUE language CLI (cuelang.org).
      If you have both installed, use the full path: #{opt_prefix}/bin/cue
    EOS
  end

  test do
    system "#{bin}/cue", "version"
  end
end
