# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CueCli < Formula
  desc "Cue CLI — coordinate events from the command line"
  homepage "https://getcue.net/cli"
  version "6.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.0.3/cue_6.0.3_darwin_amd64.tar.gz"
      sha256 "556dda1e93c834077f518a1c0d4c2d8d10a55287d1d02aaa1111db88aa8a7a7f"

      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.0.3/cue_6.0.3_darwin_arm64.tar.gz"
      sha256 "2a194ee27b4f7a32d99b5fea21c5dfe4a2bb83aee4938143473f117a8529ea2d"

      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.0.3/cue_6.0.3_linux_amd64.tar.gz"
      sha256 "ec7b7ca7c0d3371881149bf5db80cfb3d14c0beee71d14b3cb021730e6c10666"
      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.0.3/cue_6.0.3_linux_arm64.tar.gz"
      sha256 "0f59285286d0e02d0d9fce2970ff018e7a9e83e5ab4424ccba5dcbbbb34147a0"
      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
  end

  conflicts_with "cue"

  def caveats
    <<~EOS
      The 'cue' binary may conflict with the CUE language CLI (cuelang.org).
      If you have both installed, use the full path: #{opt_prefix}/bin/cue
    EOS
  end

  test do
    system "#{bin}/cue", "version"
  end
end
