# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CueCli < Formula
  desc "Cue CLI — coordinate events from the command line"
  homepage "https://getcue.net/cli"
  version "6.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.0.4/cue_6.0.4_darwin_amd64.tar.gz"
      sha256 "ccd608b9c21e138d30ca590874e570126a39f88070c51fdd174f4e19a2c36dfd"

      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.0.4/cue_6.0.4_darwin_arm64.tar.gz"
      sha256 "37a40c8308461636e4953ddd3ad96eeb6e3b844a1ba2f46ac98bc34f0e0db107"

      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.0.4/cue_6.0.4_linux_amd64.tar.gz"
      sha256 "82ca597724c8ff7c7b9fa12ff3996c7c8a53b68a0d06438e2eac47a4cc2c0e9c"
      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vegardlu/cue-cli/releases/download/v6.0.4/cue_6.0.4_linux_arm64.tar.gz"
      sha256 "69699e2371367d46f62e43f3b9203effa79207abef6c62911fde2e42953ced48"
      define_method(:install) do
        bin.install "cue"
        bash_completion.install "completions/cue.bash" => "cue"
        zsh_completion.install "completions/_cue"
        fish_completion.install "completions/cue.fish"
      end
    end
  end

  conflicts_with "cue"

  def caveats
    <<~EOS
      The 'cue' binary may conflict with the CUE language CLI (cuelang.org).
      If you have both installed, use the full path: #{opt_prefix}/bin/cue
    EOS
  end

  test do
    system "#{bin}/cue", "version"
  end
end
