# This file was generated by GoReleaser. DO NOT EDIT.
cask "cue-cli" do
  version "6.63.1"

  on_macos do
    on_intel do
      sha256 "c7135336bb5b4984cede8c6e9b528b7fb3251e278883a678baaf28fc5b5644a0"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "621754375bf5e5101bfcd82f48b36e6deeacd7e179a9d3bb822b664201fcfbaa"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ad3cc8662c93a3235865306194bc1d1a9a37c9ad9d91e9c4ccbcd84049082be"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a6b2f23651d9cd90973e2f690f8038cdd084e5475f69b6aff419042de1d7b76c"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cue-cli"
  desc "Cue CLI — coordinate events from the command line"
  homepage "https://getcue.net/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cue"
  bash_completion "completions/cue.bash"
  fish_completion "completions/cue.fish"
  zsh_completion "completions/_cue"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cue"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The 'cue' binary may conflict with the CUE language CLI (cuelang.org).
    If you have both installed, use the full path: #{staged_path}/cue
  EOS
end
