# This file was generated by GoReleaser. DO NOT EDIT.
cask "cue-cli" do
  version "6.61.1"

  on_macos do
    on_intel do
      sha256 "c9f915960d841b3d0ee0dd2949f8d3547d39feeb53cf519b4678dbaeb7042f39"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ccf2da9e33b25496ff7005a159da397671b09c2f178806f7b5bc40c60a0abe42"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e2443ba125a06ff5482203592ee5ae00abb0f97548d2e952ec67312d788e0db"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd790573451d1fd2f1b03f9e57cfe77b97948088a2301c46647dd6f0d45df6a6"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cue-cli"
  desc "Cue CLI — coordinate events from the command line"
  homepage "https://getcue.net/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cue"
  bash_completion "completions/cue.bash"
  fish_completion "completions/cue.fish"
  zsh_completion "completions/_cue"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cue"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The 'cue' binary may conflict with the CUE language CLI (cuelang.org).
    If you have both installed, use the full path: #{staged_path}/cue
  EOS
end
