# This file was generated by GoReleaser. DO NOT EDIT.
cask "cue-cli" do
  version "6.60.1"

  on_macos do
    on_intel do
      sha256 "5f3a36c55ea5747595b1b9aa1e8becf51ffb4f51398d78741dbbd46425e2f455"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b609172533a5a285481708731373f5502f719c4ce53cde7bd6a9b23b27421e2c"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "921a2ef67712caf3004eb54bfac00c9d94d863319f9b7e3438cb1d7cb267e3d8"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59ddc27e3296f9626a5d3c451681f5255bcaaa98213a742635000e4248a0c9ee"
      url "https://github.com/vegardlu/cue-cli/releases/download/v#{version}/cue_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cue-cli"
  desc "Cue CLI — coordinate events from the command line"
  homepage "https://getcue.net/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cue"
  bash_completion "completions/cue.bash"
  fish_completion "completions/cue.fish"
  zsh_completion "completions/_cue"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cue"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The 'cue' binary may conflict with the CUE language CLI (cuelang.org).
    If you have both installed, use the full path: #{staged_path}/cue
  EOS
end
